// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package parkingstatement

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StatementServiceClient is the client API for StatementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatementServiceClient interface {
	// GetParkingStatements return parking lot Statement record.
	GetParkingStatement(ctx context.Context, in *GetParkingStatementRequest, opts ...grpc.CallOption) (*GetParkingStatementResponse, error)
}

type statementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatementServiceClient(cc grpc.ClientConnInterface) StatementServiceClient {
	return &statementServiceClient{cc}
}

func (c *statementServiceClient) GetParkingStatement(ctx context.Context, in *GetParkingStatementRequest, opts ...grpc.CallOption) (*GetParkingStatementResponse, error) {
	out := new(GetParkingStatementResponse)
	err := c.cc.Invoke(ctx, "/parkingstatement.StatementService/GetParkingStatement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatementServiceServer is the server API for StatementService service.
// All implementations must embed UnimplementedStatementServiceServer
// for forward compatibility
type StatementServiceServer interface {
	// GetParkingStatements return parking lot Statement record.
	GetParkingStatement(context.Context, *GetParkingStatementRequest) (*GetParkingStatementResponse, error)
	mustEmbedUnimplementedStatementServiceServer()
}

// UnimplementedStatementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatementServiceServer struct {
}

func (UnimplementedStatementServiceServer) GetParkingStatement(context.Context, *GetParkingStatementRequest) (*GetParkingStatementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParkingStatement not implemented")
}
func (UnimplementedStatementServiceServer) mustEmbedUnimplementedStatementServiceServer() {}

// UnsafeStatementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatementServiceServer will
// result in compilation errors.
type UnsafeStatementServiceServer interface {
	mustEmbedUnimplementedStatementServiceServer()
}

func RegisterStatementServiceServer(s grpc.ServiceRegistrar, srv StatementServiceServer) {
	s.RegisterService(&StatementService_ServiceDesc, srv)
}

func _StatementService_GetParkingStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParkingStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatementServiceServer).GetParkingStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parkingstatement.StatementService/GetParkingStatement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatementServiceServer).GetParkingStatement(ctx, req.(*GetParkingStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatementService_ServiceDesc is the grpc.ServiceDesc for StatementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parkingstatement.StatementService",
	HandlerType: (*StatementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetParkingStatement",
			Handler:    _StatementService_GetParkingStatement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parking/gunk/api/parkingstatement/all.proto",
}
